### ISSUE TITLE
error: upload was rejected because the workflow run is either not in-progress...

### ISSUE THREAD

**Issue by thorn0** [codecov/codecov-action#68]
The action seems to be really flaky. Why does this happen?
```console
ERROR: The coverage upload was rejected because the workflow run is either not in-progress or finished a while ago. Please make sure the workflow run is in-progress and is not stale for uploads to process correctly.
```
https://github.com/prettier/prettier/pull/7865/checks?check_run_id=531940272#step:6:36

upd 2020-31-03: this [keeps happening](https://github.com/prettier/prettier/pull/7875/checks?check_run_id=549178432#step:6:36).

**Comment by tysonite** [comment]
This is happening for me too. For example, [there](https://github.com/tysonite/robotframework/runs/552581479?check_suite_focus=true#step:17:40).

**Comment by thorn0** [comment]
@tysonite Do you use an upload token?

**Comment by tysonite** [comment]
This issue as far as I see now happens very frequently. See [this](https://github.com/robotframework/robotframework/runs/552307162) run as an example:
1. Only 7 out of 19 jobs were succeded to upload coverage report
2. The codecove [page](https://codecov.io/gh/robotframework/robotframework/commit/7c042ca3adacb26fa40a1eb573dde2392a58e119/build) related to that shows only succesfully uploaded reports.

@thorn0, no, we switched to token-less action.

**Comment by tysonite** [comment]
@ibrahim0814, would you like to comment on that?

**Comment by ibrahim0814** [comment]
Hi all,

Thanks for bringing this to my attention. In building tokenless, I thought it would help if we added an extra security precaution where builds that have ended beyond a certain threshold would fail to upload (i.e let's say your build ended at 7pm, then you wouldn't be able to upload a report for that particular build after X number of minutes past 7pm). I'm not 100% certain, but I'm pretty sure there were issues that came about as a result of this because our X number of minutes was too small and did not account for builds that would take a long time to go through. 

I'm going to be increasing this buffer for our uploader within the next couple of days and will respond here afterwards. My hunch is that this should resolve these upload issues.

Ib

**Comment by tysonite** [comment]
@ibrahim0814, thanks for clarification. Hope this will solve the issue.

Note [usage limits](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) for GH actions, the buffer shall not be smaller than job / workflow execution / runtime, otherwise this issue will be still poping up.

**Comment by thorn0** [comment]
@ibrahim0814 We switched to using a token, but this still happens: https://github.com/prettier/prettier/pull/7951/checks?check_run_id=560657446#step:6:36

**Comment by ibrahim0814** [comment]
Hi all,

I've just merged a PR in our application which will increase this buffer. If all goes well, this change should be deployed by tomorrow

Ib

**Comment by tysonite** [comment]
This does not happen anymore, thanks for fixing.

**Comment by thorn0** [comment]
Yes, it's gone. Thank you!
